### ISSUE TITLE
Support for additional environments to generate production asset pack

### ISSUE THREAD

**Issue by spullen** [rstacruz/sinatra-assetpack#80]
I have a use case where I have a staging server and a production server. The staging server sets the RACK_ENV to :staging, however I want it to also produce the production asset pack.

I made a fork for the change I'm proposing. Would this be something that would be good for the project?

https://github.com/spullen/sinatra-assetpack/commit/6ca56cc96859ff1eba3a8fb770e94637d47d214b

https://github.com/spullen/sinatra-assetpack/commit/8d8ec4aa1a1af684c882ccc125377b4c29c1cc9b

**Comment by pjanuario** [comment]
I'm :+1: on this.
